version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=deadbeef
      - POSTGRES_USER=deadbeef
      - POSTGRES_DB=deadbeef

volumes:
  - postgres_data
