version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 1234:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=deadbeef
      - POSTGRES_USER=deadbeef
      - POSTGRES_DB=deadbeef

volumes:
  postgres_data: